# F.1 Changing Perspectives

### Codercise F.1.1. 
Given a polynomial in its coefficient representation, convert it into a value representation using NumPy's DFT/FFT module.

In [2]:
import numpy as np
def coefficients_to_values(coefficients):
    """Returns the value representation of a polynomial
    
    Args:
        coefficients (array[complex]): a 1-D array of complex 
            coefficients of a polynomial with 
            index i representing the i-th degree coefficient

    Returns: 
        array[complex]: the value representation of the 
            polynomial 
    """
    ##################
    # YOUR CODE HERE #
    ################## 
    return np.fft.fft(coefficients)

A = [4, 3, 2, 1]
print(coefficients_to_values(A))

[10.+0.j  2.-2.j  2.+0.j  2.+2.j]


### Codercise F.1.2. 
Given a polynomial in its value representation, use the NumPy's DFT/FFT module to convert from the value representation to the coefficient representation.



In [3]:
def values_to_coefficients(values):
    """Returns the coefficient representation of a polynomial
    
    Args:
        values (array[complex]): a 1-D complex array with 
            the value representation of a polynomial 

    Returns: 
        array[complex]: a 1-D complex array of coefficients
    """
    
    ##################
    # YOUR CODE HERE #
    ################## 
    return np.fft.ifft(values)


A = [10.+0.j,  2.-2.j,  2.+0.j,  2.+2.j]
print(values_to_coefficients(A))

[4.+0.j 3.+0.j 2.+0.j 1.+0.j]


### Codercise F.1.3. 
Implement a helper function nearest_power_of_2 that calculates a power of 2 that is greater than a given number.

In [ ]:
def nearest_power_of_2(x):
    """Given an integer, return the nearest power of 2. 
    
    Args:
        x (int): a positive integer

    Returns: 
        int: the nearest power of 2 of x
    """
    ##################
    # YOUR CODE HERE #
    ################## 
    return 1 if x == 0 else int(2**np.ceil(np.log2(x)))

### Codercise F.1.4. 
Given two polynomials in their coefficient representation, write a function to multiply them both using the functions coefficients_to_values, nearest_power_of_2, and values_to_coefficients.

In [27]:
def coefficients_to_values(coefficients):
    """Returns the value representation of a polynomial
    
    Args:
        coefficients (array[complex]): a 1-D array of complex 
            coefficients of a polynomial with 
            index i representing the i-th degree coefficient

    Returns: 
        array[complex]: the value representation of the 
            polynomial 
    """
    ##################
    # YOUR CODE HERE #
    ################## 
    return np.fft.fft(coefficients)

def nearest_power_of_2(x):
    """Given an integer, return the nearest power of 2. 
    
    Args:
        x (int): a positive integer

    Returns: 
        int: the nearest power of 2 of x
    """
    ##################
    # YOUR CODE HERE #
    ################## 
    return 1 if x == 0 else int(2**np.ceil(np.log2(x)))
    
def values_to_coefficients(values):
    """Returns the coefficient representation of a polynomial
    
    Args:
        values (array[complex]): a 1-D complex array with 
            the value representation of a polynomial 

    Returns: 
        array[complex]: a 1-D complex array of coefficients
    """
    
    ##################
    # YOUR CODE HERE #
    ################## 
    return np.fft.ifft(values)
def fft_multiplication(poly_a, poly_b):
    """Returns the result of multiplying two polynomials
    
    Args:
        poly_a (array[complex]): 1-D array of coefficients 
        poly_b (array[complex]): 1-D array of coefficients 

    Returns: 
        array[complex]: complex coefficients of the product
            of the polynomials
    """
    ##################
    # YOUR CODE HERE #
    ################## 

    # Calculate the number of values required
    n_va = np.max(poly_a)
    n_vb =np.max(poly_b)
    ratio = len(poly_a) / len(poly_b)
    difs = len(poly_a) - len(poly_b)
    print(ratio)
    print(difs)
    # n_va = poly_a[0]
    # n_vb = poly_b[0]

    # Figure out the nearest power of 2
    neares_a = nearest_power_of_2(n_va+n_vb+1)
    print(neares_a)
    # Pad zeros to the polynomial
    poly_a_pad = np.pad(poly_a,[0,neares_a], mode='constant')
    print(poly_a_pad)
    poly_b_pad = np.pad(poly_b, [0,neares_a+difs], mode='constant')
    print(poly_b_pad)
    # Convert the polynomials to value representation
    values_a = coefficients_to_values(poly_a_pad)    
    values_b = coefficients_to_values(poly_b_pad)

    # Multipl
    mult = values_a * values_b

    # Convert back to coefficient representation
    outs = values_to_coefficients(mult)
    
    return outs

In [29]:
A = [4, 3, 2, 1]
B = [5, 4, 3, 2, 1]
fft_multiplication(B, A)

1.25
1
16
[5 4 3 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[4 3 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


array([ 2.00000000e+01-3.38353684e-16j,  3.10000000e+01+1.51125888e-15j,
        3.40000000e+01+2.29522006e-15j,  3.00000000e+01+2.51664038e-15j,
        2.00000000e+01+1.77519437e-15j,  1.00000000e+01+2.40321833e-15j,
        4.00000000e+00+1.46477753e-15j,  1.00000000e+00+7.02329170e-16j,
        1.01506105e-15-1.48468577e-15j, -4.18712684e-15+1.28092357e-15j,
       -3.55271368e-15-4.17348735e-17j, -2.36847579e-15+1.03676756e-15j,
        5.49824736e-16+5.19238355e-16j, -4.90612841e-15+9.00100332e-16j,
       -1.01506105e-15+6.59120963e-16j,  1.69176842e-15-2.93231271e-15j,
        6.76707367e-16-7.62185142e-16j,  1.69176842e-15-1.89105784e-15j,
       -2.70682947e-15-3.69515132e-15j,  2.70682947e-15-2.98005373e-15j,
       -4.73695157e-15-2.93925441e-15j])